# config/default.yaml
env:
  id: CarRacing-v3
  render_mode: human
  continuous: false

model:
  input_shape: [3, 96, 96]
  hidden_size: 512

training:
  iterations: 30
  steps_per_iteration: 2048
  initial_human_episodes: 0
  intervention_episodes: 3
  intervention_threshold: 5
  learning_rate: 3.0e-4
  gamma: 0.99
  gae_lambda: 0.95
  clip_epsilon: 0.2
  value_coef: 0.5
  entropy_coef: 0.01
  max_grad_norm: 0.5
  batch_size: 64
  epochs: 10
  random_seed: 42

paths:
  model_dir: models
  log_dir: logs
